# Immich (Google Photos replacement) at photos.matm.icu. Listens on :2283
# (closed in the firewall); Traefik terminates TLS via selfhost.expose.
# Admin settings stay editable in the web UI (services.immich.settings unset).
{
  config,
  pkgs,
  inputs,
  ...
}:
let
  domain = "photos.matm.icu";
  port = 2283;
in
{
  services.immich = {
    enable = true;
    # 26.05 ships Immich 2.x, which is end-of-life and marked insecure; 3.x
    # only exists in unstable. The 26.05 module drives it unchanged.
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.immich;
    host = "0.0.0.0";
    inherit port;
    # Originals, thumbnails and encoded videos; on trench's local disk.
    mediaLocation = "/var/lib/immich";
    # Face and object search on the CPU (no GPU on this box).
    machine-learning.enable = true;
  };

  selfhost.expose.immich = {
    inherit domain port;
    title = "immich";
    icon = "di:immich";
  };

  # Library and database go into the nightly restic run.
  selfhost.backup.paths = [ config.services.immich.mediaLocation ];
  selfhost.backup.hostDatabases = [ "immich" ];
  selfhost.backup.exclude = [
    # Regenerated by Immich's own jobs.
    "${config.services.immich.mediaLocation}/thumbs"
    "${config.services.immich.mediaLocation}/encoded-video"
  ];
}
